### PR TITLE
Proposed changes update

### PR DESCRIPTION
**Pull request by BradyPT**
@abacaphiliac Having trouble tagging Komal, but I realized there were a couple holes in the PR regarding the Deserializer, let me know what you think. I'm mostly concerned with how I went about doing the RowMapDeserializer constructor business.

### CODE REVIEW

**Comment by abacaphiliac** [comment]
those look like great test scenarios to me.

@komibajaj ?

**Comment by komibajaj** [comment]
looks good to me, 

I think when I do encrypt_all I get just the encrypted value as json using previous code, need to verify if the new changes make that {data:encrypted_value}

Also will it encrypt data twice if I set both encrypt_data and encrypt_all true, no one should do it but it just occurred to me what if by mistake it is set what will be expected behavior. (i will test this locally too just thought to ask if you already know the answer :))

**Comment by abacaphiliac** [comment]
if the options are mutually exclusive then it would be great to check for that condition and throw a configuration exception or log the application's decision to favor one over the other.

**Comment by BradyPT** [comment]
This bit of code looks like it should stop any issues if both are set to true:
```
private DataJsonGenerator dataJsonGenerator(MaxwellOutputConfig outputConfig) throws NoSuchAlgorithmException{
		if (outputConfig.encryptData && !outputConfig.encryptAll) {
			DataJsonGenerator g = encryptingJsonGeneratorThreadLocal.get();
			return g;
		} else {
			return plaintextDataGeneratorThreadLocal.get();
		}
	}
```

**Comment by abacaphiliac** [comment]
true. worth adding a test(s) to cover those scenarios? maybe they're already covered.

**Comment by BradyPT** [comment]
Done!

**Comment by BradyPT** [comment]
I'll go ahead and merge this then :)

**Pull request merged**
