### PR TITLE
Encryption

### PR DESCRIPTION
**Pull request by BradyPT**
Added encryption without other features, fails a recovery test test on the zendesk/maxwell's travis.  
If we want to get this PR submitted there they said they wanted the whole payload encrypted with an optional prefixed kafka key, I disagree because that would create redundancy between the prefixed key and the encrypted data which would hold the same information.

### CODE REVIEW

**Comment by abacaphiliac** [comment]
looks cool @BradyPT . i know you're working on another flag for encryption-level or strategy. i look froward to seeing that.

is there a way to decrypt? would be neat if the inverse op was provided by the same package/class so that i can do my decryption in my consumer via Maxwell-as-a-jar.

**Comment by BradyPT** [comment]
@abacaphiliac I'm looking at merging this into master now and seeing how the zendesk people like it. I'll probably have to take some time digging into the kafka functionality and make sure everything's working there but this is pretty effective at reaching a general use case right now. +1?

**Comment by abacaphiliac** [comment]
+1 @BradyPT yes looks good to me. i'm so sorry, i skipped over this email.

**Comment by BradyPT** [comment]
@abacaphiliac Revisiting this now, we're thinking that we should perhaps squash our old PR and kick up a new one to see if we can get attention again. Do we bother merging the encryption branch into master here or should we just shoot it straight over to their master?

**Comment by abacaphiliac** [comment]
i personally wouldn't merge into a fork's master, because you might have multiple feature branches pending an upstream merge. in that scenario you wouldn't want to merge multiple features into master and wait for master to be merged upstream. i usually keep feature branches separate and let my fork's master branch go stale.

good luck on the revisit! let me know if i can help.

**Comment by BradyPT** [comment]
Thanks, a couple things I hadn't thought of there :)

**Pull request closed without merging**
